server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          #lower-case-service-id: true
      routes:
        - id: cambio-service-id         # apenas o identificador desta configuracao de rota
          uri: lb://cambio-ms           # define o destino da rota "cambio-ms" -> nome do micrsservico configurado no application.yml
          predicates:                   # path na url ex: localhost:8080/cambio-service/algo-aqui
            - Path=/cambio/**   # uri base do controller e ** tudo que tiver depois
          filters:
            - RewritePath=/cambio/(?<path>.*), /$\{path}
        - id: book-service-id
          uri: lb://book-ms
          predicates:
            - Path=/book/**
          filters:
            - RewritePath=/book/(?<path>.*), /$\{path}
        - id: open-api
          uri: lb://gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

#      routes:
#        - id: cambio-service-id         # apenas o identificador desta configuracao de rota
#          uri: lb://cambio-ms           # define o destino da rota "cambio-ms" -> nome do micrsservico configurado no application.yml
#          predicates: # path na url ex: localhost:8080/cambio-service/algo-aqui
#            - Path=/cambio-service/**   # uri base do controller e ** tudo que tiver depois
#          filters:
#            - RewritePath=/cambio-service/(?<path>.*), /$\{path}
#        - id: book-service-id
#          uri: lb://book-ms
#          predicates:
#            - Path=/book-service/**
#          filters:
#            - RewritePath=/book-service/(?<path>.*), /$\{path}
#        - id: open-api
#          uri: lb://gateway
#          predicates:
#            - Path=/v3/api-docs/**
#          filters:
#            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: book
        url: /v3/api-docs/book
      - name: cambio
        url: /v3/api-docs/cambio

management:   # configuração da observalidade do zipkin e micrometer tracin
  tracing:
    sampling:
      probability: 1.0  # 100% de todas as requisicoes e respostas - nao eh bom por questoes de perfomance
#springdoc:
#  swagger-ui:
#    urls:
#      - name: book
#        url: /v3/api-docs/book-service
#      - name: cambio
#        url: /v3/api-docs/cambio-service