name: CI with Github
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Log in to DockerHub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.0
        with:
          java-version: '17'
          distribution: 'corretto'
          
      - name: Build Eureka Naming Server Contaier Image
        working-directory: ./naming-server
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build API Gateway Container Image
        working-directory: ./gateway
        run: mvn spring-boot:build-image -DskipTests

      - name: Build Cambio Microservice Jar
        working-directory: ./cambio-ms
        run: mvn clean package -DskipTests
        
      - name: Build Book Microservice Jar
        working-directory: ./book-ms
        run: mvn clean package -DskipTests

      - name: Docker Compose Build
        working-directory: .
        run: docker compose build

